### ISSUE TITLE
Not compatible With Anki 2.1.21beta

### ISSUE THREAD

**Issue by silentcicada1** [Arthur-Milchior/anki-time-in-browser#1]
This add on is super useful but is not compatible With Anki 2.1.21. Thank you for putting out such a useful add on and I hope that it will be maintained for future versions of anki.

**Comment by silentcicada1** [comment]
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.21 (8960d12a) Python 3.8.0 Qt 5.13.1 PyQt 5.14.1
Platform: Mac 10.15.1
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2020-03-07 21:38:10
Add-ons possibly involved: ⁨Showing time in browser, Advanced Browser⁩

Caught exception:
Traceback (most recent call last):
  File "/Users/rachelstandifird/Library/Application Support/Anki2/addons21/874215009/advancedbrowser/core.py", line 94, in data
    return super(AdvancedDataModel, self).data(index, role)
  File "aqt/browser.py", line 145, in data
  File "/Users/rachelstandifird/Library/Application Support/Anki2/addons21/874215009/advancedbrowser/core.py", line 98, in columnData
    returned = self._columnData(self, index)
  File "/Users/rachelstandifird/Library/Application Support/Anki2/addons21/1243668133/init.py", line 53, in columnData
    return fmtTimeSpan(c.ivl*86400)
NameError: name 'fmtTimeSpan' is not defined

Caught exception:
Traceback (most recent call last):
  File "/Users/rachelstandifird/Library/Application Support/Anki2/addons21/874215009/advancedbrowser/core.py", line 94, in data
    return super(AdvancedDataModel, self).data(index, role)
  File "aqt/browser.py", line 145, in data
  File "/Users/rachelstandifird/Library/Application Support/Anki2/addons21/874215009/advancedbrowser/core.py", line 98, in columnData
    returned = self._columnData(self, index)
  File "/Users/rachelstandifird/Library/Application Support/Anki2/addons21/1243668133/init.py", line 53, in columnData
    return fmtTimeSpan(c.ivl*86400)
NameError: name 'fmtTimeSpan' is not defined

Caught exception:
Traceback (most recent call last):
  File "/Users/rachelstandifird/Library/Application Support/Anki2/addons21/874215009/advancedbrowser/core.py", line 94, in data
    return super(AdvancedDataModel, self).data(index, role)
  File "aqt/browser.py", line 145, in data
  File "/Users/rachelstandifird/Library/Application Support/Anki2/addons21/874215009/advancedbrowser/core.py", line 98, in columnData
    returned = self._columnData(self, index)
  File "/Users/rachelstandifird/Library/Application Support/Anki2/addons21/1243668133/init.py", line 53, in columnData
    return fmtTimeSpan(c.ivl*86400)
NameError: name 'fmtTimeSpan' is not defined

Caught exception:
Traceback (most recent call last):
  File "/Users/rachelstandifird/Library/Application Support/Anki2/addons21/874215009/advancedbrowser/core.py", line 94, in data
    return super(AdvancedDataModel, self).data(index, role)
  File "aqt/browser.py", line 145, in data
  File "/Users/rachelstandifird/Library/Application Support/Anki2/addons21/874215009/advancedbrowser/core.py", line 98, in columnData
    returned = self._columnData(self, index)
  File "/Users/rachelstandifird/Library/Application Support/Anki2/addons21/1243668133/init.py", line 53, in columnData
    return fmtTimeSpan(c.ivl*86400)
NameError: name 'fmtTimeSpan' is not defined

Caught exception:
Traceback (most recent call last):
  File "/Users/rachelstandifird/Library/Application Support/Anki2/addons21/874215009/advancedbrowser/core.py", line 94, in data
    return super(AdvancedDataModel, self).data(index, role)
  File "aqt/browser.py", line 145, in data
  File "/Users/rachelstandifird/Library/Application Support/Anki2/addons21/874215009/advancedbrowser/core.py", line 98, in columnData
    returned = self._columnData(self, index)
  File "/Users/rachelstandifird/Library/Application Support/Anki2/addons21/1243668133/init.py", line 53, in columnData
    return fmtTimeSpan(c.ivl*86400)
NameError: name 'fmtTimeSpan' is not defined

Caught exception:
Traceback (most recent call last):
  File "/Users/rachelstandifird/Library/Application Support/Anki2/addons21/874215009/advancedbrowser/core.py", line 94, in data
    return super(AdvancedDataModel, self).data(index, role)
  File "aqt/browser.py", line 145, in data
  File "/Users/rachelstandifird/Library/Application Support/Anki2/addons21/874215009/advancedbrowser/core.py", line 98, in columnData
    returned = self._columnData(self, index)
  File "/Users/rachelstandifird/Library/Application Support/Anki2/addons21/1243668133/init.py", line 53, in columnData
    return fmtTimeSpan(c.ivl*86400)
NameError: name 'fmtTimeSpan' is not defined

Caught exception:
Traceback (most recent call last):
  File "/Users/rachelstandifird/Library/Application Support/Anki2/addons21/874215009/advancedbrowser/core.py", line 94, in data
    return super(AdvancedDataModel, self).data(index, role)
  File "aqt/browser.py", line 145, in data
  File "/Users/rachelstandifird/Library/Application Support/Anki2/addons21/874215009/advancedbrowser/core.py", line 98, in columnData
    returned = self._columnData(self, index)
  File "/Users/rachelstandifird/Library/Application Support/Anki2/addons21/1243668133/init.py", line 53, in columnData
    return fmtTimeSpan(c.ivl*86400)
NameError: name 'fmtTimeSpan' is not defined

Caught exception:
Traceback (most recent call last):
  File "/Users/rachelstandifird/Library/Application Support/Anki2/addons21/874215009/advancedbrowser/core.py", line 94, in data
    return super(AdvancedDataModel, self).data(index, role)
  File "aqt/browser.py", line 145, in data
  File "/Users/rachelstandifird/Library/Application Support/Anki2/addons21/874215009/advancedbrowser/core.py", line 98, in columnData
    returned = self._columnData(self, index)
  File "/Users/rachelstandifird/Library/Application Support/Anki2/addons21/1243668133/init.py", line 53, in columnData
    return fmtTimeSpan(c.ivl*86400)
NameError: name 'fmtTimeSpan' is not defined

Caught exception:
Traceback (most recent call last):
  File "/Users/rachelstandifird/Library/Application Support/Anki2/addons21/874215009/advancedbrowser/core.py", line 94, in data
    return super(AdvancedDataModel, self).data(index, role)
  File "aqt/browser.py", line 145, in data
  File "/Users/rachelstandifird/Library/Application Support/Anki2/addons21/874215009/advancedbrowser/core.py", line 98, in columnData
    returned = self._columnData(self, index)
  File "/Users/rachelstandifird/Library/Application Support/Anki2/addons21/1243668133/init.py", line 53, in columnData
    return fmtTimeSpan(c.ivl*86400)
NameError: name 'fmtTimeSpan' is not defined

Caught exception:
Traceback (most recent call last):
  File "/Users/rachelstandifird/Library/Application Support/Anki2/addons21/874215009/advancedbrowser/core.py", line 94, in data
    return super(AdvancedDataModel, self).data(index, role)
  File "aqt/browser.py", line 145, in data
  File "/Users/rachelstandifird/Library/Application Support/Anki2/addons21/874215009/advancedbrowser/core.py", line 98, in columnData
    returned = self._columnData(self, index)
  File "/Users/rachelstandifird/Library/Application Support/Anki2/addons21/1243668133/init.py", line 53, in columnData
    return fmtTimeSpan(c.ivl*86400)
NameError: name 'fmtTimeSpan' is not defined

Caught exception:
Traceback (most recent call last):
  File "/Users/rachelstandifird/Library/Application Support/Anki2/addons21/874215009/advancedbrowser/core.py", line 94, in data
    return super(AdvancedDataModel, self).data(index, role)
  File "aqt/browser.py", line 145, in data
  File "/Users/rachelstandifird/Library/Application Support/Anki2/addons21/874215009/advancedbrowser/core.py", line 98, in columnData
    returned = self._columnData(self, index)
  File "/Users/rachelstandifird/Library/Application Support/Anki2/addons21/1243668133/init.py", line 53, in columnData
    return fmtTimeSpan(c.ivl*86400)
NameError: name 'fmtTimeSpan' is not defined

Caught exception:
Traceback (most recent call last):
  File "/Users/rachelstandifird/Library/Application Support/Anki2/addons21/874215009/advancedbrowser/core.py", line 94, in data
    return super(AdvancedDataModel, self).data(index, role)
  File "aqt/browser.py", line 145, in data
  File "/Users/rachelstandifird/Library/Application Support/Anki2/addons21/874215009/advancedbrowser/core.py", line 98, in columnData
    returned = self._columnData(self, index)
  File "/Users/rachelstandifird/Library/Application Support/Anki2/addons21/1243668133/init.py", line 53, in columnData
    return fmtTimeSpan(c.ivl*86400)
NameError: name 'fmtTimeSpan' is not defined

Caught exception:
Traceback (most recent call last):
  File "/Users/rachelstandifird/Library/Application Support/Anki2/addons21/874215009/advancedbrowser/core.py", line 94, in data
    return super(AdvancedDataModel, self).data(index, role)
  File "aqt/browser.py", line 145, in data
  File "/Users/rachelstandifird/Library/Application Support/Anki2/addons21/874215009/advancedbrowser/core.py", line 98, in columnData
    returned = self._columnData(self, index)
  File "/Users/rachelstandifird/Library/Application Support/Anki2/addons21/1243668133/init.py", line 53, in columnData
    return fmtTimeSpan(c.ivl*86400)
NameError: name 'fmtTimeSpan' is not defined

Caught exception:
Traceback (most recent call last):
  File "/Users/rachelstandifird/Library/Application Support/Anki2/addons21/874215009/advancedbrowser/core.py", line 94, in data
    return super(AdvancedDataModel, self).data(index, role)
  File "aqt/browser.py", line 145, in data
  File "/Users/rachelstandifird/Library/Application Support/Anki2/addons21/874215009/advancedbrowser/core.py", line 98, in columnData
    returned = self._columnData(self, index)
  File "/Users/rachelstandifird/Library/Application Support/Anki2/addons21/1243668133/init.py", line 53, in columnData
    return fmtTimeSpan(c.ivl*86400)
NameError: name 'fmtTimeSpan' is not defined

Caught exception:
Traceback (most recent call last):
  File "/Users/rachelstandifird/Library/Application Support/Anki2/addons21/874215009/advancedbrowser/core.py", line 94, in data
    return super(AdvancedDataModel, self).data(index, role)
  File "aqt/browser.py", line 145, in data
  File "/Users/rachelstandifird/Library/Application Support/Anki2/addons21/874215009/advancedbrowser/core.py", line 98, in columnData
    returned = self._columnData(self, index)
  File "/Users/rachelstandifird/Library/Application Support/Anki2/addons21/1243668133/init.py", line 53, in columnData
    return fmtTimeSpan(c.ivl*86400)
NameError: name 'fmtTimeSpan' is not defined

Caught exception:
Traceback (most recent call last):
  File "/Users/rachelstandifird/Library/Application Support/Anki2/addons21/874215009/advancedbrowser/core.py", line 94, in data
    return super(AdvancedDataModel, self).data(index, role)
  File "aqt/browser.py", line 145, in data
  File "/Users/rachelstandifird/Library/Application Support/Anki2/addons21/874215009/advancedbrowser/core.py", line 98, in columnData
    returned = self._columnData(self, index)
  File "/Users/rachelstandifird/Library/Application Support/Anki2/addons21/1243668133/init.py", line 53, in columnData
    return fmtTimeSpan(c.ivl*86400)
NameError: name 'fmtTimeSpan' is not defined

**Comment by Arthur-Milchior** [comment]
Thank you. For some reason this add-on was not installed on my computer, I had missed this bug. It'll be corrected shortly

**Comment by Arthur-Milchior** [comment]
Please update and let me know if it works.
I haven't installed the beta yet

**Comment by silentcicada1** [comment]
It is saying it requires anki ≤2.1.20 in order to run

**Comment by Arthur-Milchior** [comment]
That's quite strange. I create a 2.1.21 version. It is a different code than the 2.1.20 indeed, but it's uploaded too.
Can you make a post on https://anki.tenderapp.com/ to tell Damien that beta version can't download the version of add-ons created for them. Which is a problem because you can't test my solution anymore
